(eval-when-compile    (require 'color-theme))
(defun color-theme-github ()
  "Color theme by Dudley Flanders, created 2008-07-11."
  (interactive)
  (color-theme-install
   '(color-theme-github
     ((background-color . "#f8f8ff")
      (background-mode . light)
      (border-color . "black")
      (cursor-color . "#a7a7a7")
      (foreground-color . "#000000")
      (mouse-color . "sienna1"))
     ()
     (default ((t (:stipple nil :background "#f8f8ff" :foreground "#000000" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal))))
     (cursor ((t (:background "#a7a7a7"))))
     (font-lock-builtin-face ((t (nil))))
     (font-lock-comment-delimiter-face ((t (:italic t :slant italic :foreground "#999988"))))
     (font-lock-comment-face ((t (:italic t :foreground "#999988" :slant italic))))
     (font-lock-constant-face ((t (:foreground "#990073"))))
     (font-lock-doc-face ((t (:foreground "#dd1144"))))
     (font-lock-function-name-face ((t (:foreground "#990000"))))
     (font-lock-keyword-face ((t (:bold t :weight bold))))
     (font-lock-negation-char-face ((t (nil))))
     (font-lock-reference-face ((t (nil))))
     (font-lock-regexp-grouping-backslash ((t (:foreground "#009926"))))
     (font-lock-regexp-grouping-construct ((t (:foreground "#009926"))))
     (font-lock-string-face ((t (:foreground "#dd1144"))))
     (font-lock-type-face ((t (:foreground "#990000"))))
     (font-lock-variable-name-face ((t (:foreground "#008080"))))
     (highlight ((t (:background "#acc3e6"))))
     (link ((t (:foreground "blue1" :underline t))))
     (link-visited ((t (:underline t :foreground "magenta4"))))
     (region ((t (:background "#bcd5fa"))))
     (show-paren-match ((t (:background "#acc3e6"))))
     (show-paren-mismatch ((t (:background "#dd1144")))))))
(add-to-list 'color-themes '(color-theme-github  "GitHub" "Dudley Flanders"))
